trainer_constructor_data: !ConstructorData
  constructor: !function algatross.environments.runners.SingleAgentRLRunner
  config:
    rollout_config:
      batch_size: 128
      gamma: 0.85
      gae_lambda: 0.85
    train_config:
      device: cpu
      sgd_minibatch_size: 16
      num_sgd_iter: 16
training_agents: [deputy_0]
ally_teams:
  allies_0:
    - deputy_0
    - deputy_1
conspecific_data_keys: []
conspecific_utility_keys: []
fitness_metric_keys:
  - rewards
fitness_metric_optimization_type:
  - max
fitness_multiplier:
  - 1.0
fitness_reduce_fn: sum
max_envs: 2
