default_language_version:
  python: python3.10
repos:
  # Start built-in hooks from pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files
        name: Check for added large files
        description: Prevent giant files from being committed
      - id: check-case-conflict
        name: Check for case conflicts
        description: Check for files that would conflict in case-insensitive filesystems
      - id: check-toml
        name: Check TOML
        description: Checks toml files for parseable syntax
      - id: check-json
        name: Check JSON
        description: This hook checks json files for parseable syntax.
        exclude: "(.devcontainer/devcontainer.json|.vscode/launch.json|.vscode/tasks.json)"
      - id: pretty-format-json
        name: Pretty format JSON
        description: This hook sets a standard for formatting JSON files.
        exclude: "(.devcontainer/devcontainer.json|.devcontainer/10_nvidia.json|.vscode/.*|.*.ipynb)"
        args: ["--no-sort-keys", "--indent", "4", "--autofix"]
        stages: [pre-commit]
      - id: check-merge-conflict
        name: Check for merge conflicts
        description: Check for files that contain merge conflict strings.
      - id: check-symlinks
        name: Check for broken symlinks
        description: Checks for symlinks which do not point to anything.
      - id: check-yaml
        name: Check Yaml
        description: This hook checks yaml files for parseable syntax.
        exclude: "(^config.*|^test.*|^docs.*|mkdocs.yml$|.*/_templates/.*.yml|.gitlab-ci.y[a]?ml$)"
        args: ["--allow-multiple-documents"]
      - id: trailing-whitespace
        name: Trim Whitespace
        description: Trims trailing whitespace
        exclude_types:
          - "markdown"
          - "python" # ruff will take care of this
      - id: detect-private-key
        name: Detect Private Key
        description: Detects the presence of private keys
      - id: no-commit-to-branch
        name: "Don't commit to branch"
        entry: no-commit-to-branch
        args: ["--branch", "master", "--branch", "develop", "--branch", "main"]
  - repo: https://github.com/Yelp/detect-secrets
    rev: "v1.5.0"
    hooks:
      - id: detect-secrets
        name: Detect secrets
        description: Detects high entropy strings that are likely to be passwords.
        args:
          - "--baseline"
          - ".secrets.baseline"
  - repo: https://github.com/gitleaks/gitleaks
    rev: "v8.21.2"
    hooks:
      - id: gitleaks
        name: Detect hardcoded secrets
        description: Detect hardcoded secrets using Gitleaks
        exclude: ".secrets.baseline"
  # Start misc lint & formatters
  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: "v0.7.3"
    hooks:
      - id: pydocstringformatter
        description: Automatically format your Python docstrings
  - repo: https://github.com/openstack/bashate
    rev: "2.1.1"
    hooks:
      - id: bashate
        name: Bashate
        description: This hook runs bashate for linting shell scripts
        args: ["--ignore=E003,E006,E010,E040"]
        verbose: false
  - repo: https://github.com/hadolint/hadolint
    rev: "v2.13.1-beta"
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        description: Runs hadolint Docker image to lint Dockerfiles
        args: ["-c", ".hadolint.yaml"]
        exclude: "^(.*docs/man.*)$"
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.15.0
    hooks:
      - id: markdownlint-cli2
        name: Lint markdown
        description: Runs markdownlint-cli2 to lint markdown
        alias: markdownlint
        # language: system
        exclude: "^(.*docs/man.*.md|CHANGELOG.md)$"
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: Lint YAML Files
        description: Run `yamllint` on YAML files
  # Start python linters
  - repo: https://github.com/numpy/numpydoc
    rev: "v1.8.0"
    hooks:
      - id: numpydoc-validation
        files: algatross
        exclude: '\.dagger'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      - id: ruff-format
        files: algatross
        description: "Run 'ruff format' for extremely fast Python formatting"
      - id: ruff
        name: ruff
        files: algatross
        description: An extremely fast Python linter, written in Rust.
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: mypy
        description: Optional static typing for Python
        files: algatross
        entry: uv run mypy
        exclude: '(algatross/algorithms/genetic/mo_aim/archipelago/dask_archipelago\.py$)|.dagger'
        additional_dependencies:
          - "ray==2.9.3"
          - "numpy==1.26.4"
          - "torch==1.13.0"
          - "types-pyyaml==6.0.12.20240917"
          - "types-pytz"
          - "types-setuptools"
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.7
    hooks:
      - id: uv-lock
        args:
          - "--locked"
  - repo: https://git.act3-ace.com/devsecops/act3-pt
    rev: "v2.2.1"
    hooks:
      - id: blueprint-lint
      - id: blueprint-update-check
