archipelago_training_iterations: 0
batch_size: 2000
epochs: 10
island_iterations: 5
mainland_iterations: 1
num_sgd_iters: 100
run_id: 0
save_root: save/mo-marl/autogen/081924-223857/1000/0
seed: 1000
sgd_minibatch_size: 1000
sigma: 0.1
tag: ''
uda_training_iterations: 20
