trainer_constructor_data: !ConstructorData
  constructor: !function algatross.environments.mpe.simple_tag.MPESimpleTagRunner
  config:
    rollout_config:
      batch_size: 300
training_agents:
  - agent_0
  - agent_1
ally_teams:
  allies_0:
    - agent_0
    - agent_1
opponent_teams:
  adversaries_0:
    - adversary_0
    - adversary_1
    - adversary_2
conspecific_data_keys:
  - obs
  - actions
conspecific_utility_keys:
  - tag_score
  - minimum_ally_speed
  - minimum_adversary_speed
  - closest_ally_distance
  - closest_adversary_distance
  - closest_landmark_distance
  - boundary_penalty
fitness_metric_keys:
  - tag_score
  - minimum_ally_speed
  - minimum_adversary_speed
  - closest_ally_distance
  - closest_adversary_distance
  - closest_landmark_distance
  - boundary_penalty
fitness_metric_optimization_type:
  - max
  - min
  - max
  - min
  - max
  - min
  - max
fitness_reduce_fn: null
