n_units: 20
n_enemies: 20
team_gen:
  n_units: 20
  n_enemies: 20
  dist_type: "weighted_teams"
  unit_types:
    - "stalker"
    - "zealot"
    - "colossus"
  weights:
    - 0.45
    - 0.45
    - 0.1
  observe: True
start_positions:
  dist_type: "surrounded_and_reflect"
  p: 0.5
  map_x: 32
  map_y: 32
# enemy_mask:
#   dist_type: "mask"
#   mask_probability: 0.5
#   n_enemies: 5
