n_units: 10
n_enemies: 10
team_gen:
  n_units: 10
  n_enemies: 10
  dist_type: "weighted_teams"
  unit_types:
    - "marine"
    - "marauder"
    - "medivac"
  weights:
    - 0.45
    - 0.45
    - 0.1
  exception_unit_types:
    - "medivac"
  observe: True

start_positions:
  dist_type: "surrounded_and_reflect"
  p: 0.5
  map_x: 32
  map_y: 32
# enemy_mask:
#   dist_type: "mask"
#   mask_probability: 0.5
#   n_enemies: 5
