n_units: 20
n_enemies: 23
team_gen:
  n_units: 20
  n_enemies: 23
  dist_type: "weighted_teams"
  unit_types:
    - "zergling"
    - "baneling"
    - "hydralisk"
  weights:
    - 0.45
    - 0.1
    - 0.45
  exception_unit_types:
    - "baneling"
  observe: True

start_positions:
  dist_type: "surrounded_and_reflect"
  p: 0.5
  map_x: 32
  map_y: 32
# enemy_mask:
#   dist_type: "mask"
#   mask_probability: 0.5
#   n_enemies: 5
