critic_outs: 1
shared_encoder: False
free_log_std: False
entropy_coeff: 0.0
kl_target: 0.2
kl_coeff: 0.2
vf_coeff: 1.0
logp_clip_param: 0.2
vf_clip_param: Null
optimizer_class: !function torch.optim.Adam
optimizer_kwargs:
  lr: 0.0003
